max_clock = 3000000
clock_granu = 1
log_level = "INFO"
log_name = "output/sample-bus.csv"
edges = [
    [
        "Host-0",
        "Switch-1",
    ],
    [
        "Host-1",
        "Switch-1",
    ],
    [
        "Host-2",
        "Switch-1",
    ],
    [
        "Host-3",
        "Switch-1",
    ],
    [
        "Switch-2",
        "Mem-0",
    ],
    [
        "Switch-2",
        "Mem-1",
    ],
    [
        "Switch-2",
        "Mem-2",
    ],
    [
        "Switch-2",
        "Mem-3",
    ],
    [
        "Switch-1",
        "Bus",
    ],
    [
        "Bus",
        "Switch-2",
    ],
]

[devices]
Host-0 = "Requester"
Host-1 = "Requester"
Host-2 = "Requester"
Host-3 = "Requester"
Mem-0 = "DRAMsim3Interface"
Mem-1 = "DRAMsim3Interface"
Mem-2 = "DRAMsim3Interface"
Mem-3 = "DRAMsim3Interface"
Switch-1 = "Switch"
Switch-2 = "Switch"
Bus = "DuplexBus"

[Host-0]
q_capacity = 32
cache_capacity = 8192
cache_delay = 12
issue_delay = 0
coherent = false
burst_size = 1
block_size = 64
interleave_type = "random"
interleave_param = 500
hot_req_ratio = 0.5
hot_region_ratio = 0.5
trace_file = ""

[Host-1]
q_capacity = 32
cache_capacity = 8192
cache_delay = 12
issue_delay = 0
coherent = false
burst_size = 1
block_size = 64
interleave_type = "random"
interleave_param = 500
hot_req_ratio = 0.5
hot_region_ratio = 0.5
trace_file = ""

[Host-2]
q_capacity = 32
cache_capacity = 8192
cache_delay = 12
issue_delay = 0
coherent = false
burst_size = 1
block_size = 64
interleave_type = "random"
interleave_param = 500
hot_req_ratio = 0.5
hot_region_ratio = 0.5
trace_file = ""

[Host-3]
q_capacity = 32
cache_capacity = 8192
cache_delay = 12
issue_delay = 0
coherent = false
burst_size = 1
block_size = 64
interleave_type = "random"
interleave_param = 500
hot_req_ratio = 0.5
hot_region_ratio = 0.5
trace_file = ""

[Mem-0]
tick_per_clock = 1
process_time = 40
start = 0
capacity = 1073741824
wr_ratio = 0.25
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[Mem-1]
tick_per_clock = 1
process_time = 40
start = 0
capacity = 1073741824
wr_ratio = 0.25
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[Mem-2]
tick_per_clock = 1
process_time = 40
start = 0
capacity = 1073741824
wr_ratio = 0.25
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[Mem-3]
tick_per_clock = 1
process_time = 40
start = 0
capacity = 1073741824
wr_ratio = 0.25
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[Switch-1]
delay = 0

[Switch-2]
delay = 0

[Bus]
is_full = true
half_rev_time = 100
delay_per_T = 1
width = 32
framing_time = 20
frame_size = 64


